Added config subcommand initial code for testing

diff --git a/gitsprint-common b/gitsprint-common
--- a/gitsprint-common
+++ b/gitsprint-common
@@ -96,6 +96,11 @@ git_config_bool_exists() {
 	[ "$value" = "true" ]
 }
 
+git_branch_exists() {
+	[ -n "$1" ] || die "Missing branch name"
+	git_local_branch_exists "$1" || git_remote_branch_exists "$ORIGIN/$1"
+}
+
 
 # gitsprint_override_flag_boolean()
 #
@@ -146,8 +151,55 @@ gitsprint_is_initialized() {
 	git config --get-regexp gitsprint.prefix >/dev/null 2>&1
 }
 
+# Loading settings that can be overridden using git config
+gitsprint_load_settings() {
+	export GIT_CURRENT_REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null)"
+	DOT_GIT_DIR=$(git rev-parse --git-dir)
+	export DOT_GIT_DIR="$(cd ${DOT_GIT_DIR} >/dev/null 2>&1 && pwd)"
+	export HOOKS_DIR="$(git config --get gitsprint.path.hooks)"
+	export MASTER_BRANCH=$(git config --get gitsprint.branch.master)
+	export DEVELOP_BRANCH=$(git config --get gitsprint.branch.develop)
+	export ORIGIN=$(git config --get gitsprint.origin || echo origin)
+
+	GITSPRINT_CONFIG="$DOT_GIT_DIR/gitsprint_config"
+	if [ -f "$GITSPRINT_CONFIG" ]; then # move all settings from old .git/gitsprint_config to the local conf.
+		warn "Migrating old \"$GITSPRINT_CONFIG\" to the \"--local\" repo config."
+		_config_lines=`git config --list --file="$GITSPRINT_CONFIG"`;
+		for _config_line in ${_config_lines}; do
+			_key=${_config_line%=*}
+			_value=${_config_line#=*}
+			git_do config --local gitsprint.${_key} ${_value}
+		done;
+		mv "$GITSPRINT_CONFIG" "$GITSPRINT_CONFIG".backup 2>/dev/null
+	fi
+}
+
+#
+# Update the config with the base of a new git-sprint branch.
+#
+# @param $1 Base of the new branch
+# @param $2 Name of the branch
+#
+gitsprint_config_set_base_branch() {
+	local base branch
+
+	base=$1
+	branch=$2
+	$(git_do config --local "gitsprint.branch.$branch.base" $base)
+}
+
 #
 # Assertions for use in git-sprint subcommands
+#
+require_git_repo() {
+	git rev-parse 2>/dev/null || die "Not a git repository"
+}
+
+require_gitsprint_initialized() {
+	gitsprint_is_initialized || die "Not a gitsprint-enabled repo yet. Please run 'git sprint init' first."
+	$(git config --get gitsprint.data.sprintNumber >/dev/null 2>&1) || die "Sprint Number not set. Please run 'git sprint init'."
+}
+
 require_clean_working_tree() {
 	local result
 
@@ -159,6 +211,10 @@ require_clean_working_tree() {
 	if [ $result -eq 2 ]; then
 		die "Index contains uncommited changes. Aborting."
 	fi
+}
+
+require_branch() {
+	git_branch_exists "$1" || die "Branch '$1' does not exist and is required."
 }
 
 #
